name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Build the Docker image
        run: docker build --platform=linux/amd64 -t 20522153/thaibaoattendance:latest .

      - name: Log in to Docker Hub
        run: docker login -u 20522153 -p 123456789

      - name: Push Docker image to Docker Hub
        run: docker push 20522153/thaibaoattendance:latest 
        
      - name: trigger render
        run:  curl https://api.render.com/deploy/srv-comt3621hbls73f90kdg?key=JPQf0v1ny_M